services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: project_db
    ports:
      - "3306:3306"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # phpMyAdmin のポートを8081に設定
    environment:
      PMA_HOST: db  # phpMyAdmin が接続する MySQL コンテナの名前
      PMA_USER: root
      PMA_PASSWORD: rootpassword  # MySQLのrootパスワード
    depends_on:
      - db
